// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/panupakm/miniredis/internal/db"
	"github.com/panupakm/miniredis/internal/pubsub"
	"github.com/panupakm/miniredis/server"
)

// Injectors from wire.go:

func InitializeServer() *server.Server {
	dbDb := db.NewDb()
	pubSub := pubsub.NewPubSub()
	serverServer := server.NewServer(dbDb, pubSub)
	return serverServer
}
