// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/panupakm/miniredis/server"
	"github.com/panupakm/miniredis/server/pubsub"
	"github.com/panupakm/miniredis/server/storage"
)

// Injectors from wire.go:

func InitializeServer() *server.Server {
	storageStorage := storage.NewDefaultStorage()
	pubSub := pubsub.NewDefaultPubSub()
	serverServer := server.NewServer(storageStorage, pubSub)
	return serverServer
}
